/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:27ccb619-b6b8-421e-8679-f4edefa4b722",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_qCIcWtXEH",
    "aws_user_pools_web_client_id": "r4b89aokov0lnee81q4362oe1",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://r254dobszrcstp5xzoojqgr7hq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
